[build]
command = "cd backend && python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
PYTHON_VERSION = "3.11"
PORT = "8001"

[environments.production]
command = "cd backend && python server.py"